extends Node


# TODO: Change this before submitting.
const IS_DEBUG := true

const WORLD_COLLISION_MASK := 1
const ENEMY_COLLISION_MASK := 2
const PLAYER_COLLISION_MASK := 4
const COLLIDABLE_COLLISION_MASK := \
    WORLD_COLLISION_MASK | ENEMY_COLLISION_MASK | PLAYER_COLLISION_MASK
